// Mock data - replace with actual data fetching

export const mockStatusOptions = [
  { value: "", label: "Todos os status" },
  { value: "open", label: "Aberto" },
  { value: "in-progress", label: "Em andamento" },
  { value: "resolved", label: "Resolvido" },
];
export const mockPriorityOptions = [
  { value: "", label: "Todas as prioridades" },
  { value: "urgent", label: "Urgente" },
  { value: "medium", label: "Média" },
  { value: "low", label: "Baixa" },
];
export const mockAssigneeOptions = [
  { value: "", label: "Todos os responsáveis" },
  { value: "Ana Silva", label: "Ana Silva" },
  { value: "João Costa", label: "João Costa" },
  { value: "Carlos Lima", label: "Carlos Lima" },
  { value: "Anderson Freitas", label: "Anderson Freitas" },
];

export const mockTickets = [
  {
    id: "TK001",
    priority: "urgent" as const,
    clientName: "Ricardo Leite",
    clientEmail: "ricardo@email.com",
    subject: "Solicitação de alteração",
    status: "open" as const,
    createdAt: "14/12/2024",
    assignee: "Ana Silva",
  },
  {
    id: "TK002",
    priority: "medium" as const,
    clientName: "Maria Silva",
    clientEmail: "mariasilva@email.com",
    subject: "Dúvida sobre cobertura",
    status: "open" as const,
    createdAt: "13/12/2024",
    assignee: "João Costa",
  },
  {
    id: "TK003",
    priority: "low" as const,
    clientName: "João Costa",
    clientEmail: "costajoao@email.com",
    subject: "Sinistro na residência",
    status: "in-progress" as const,
    createdAt: "13/12/2024",
    assignee: "Carlos Lima",
  },
  {
    id: "TK004",
    priority: "urgent" as const,
    clientName: "Residencial Premium",
    clientEmail: "rpremium@email.com",
    subject: "Seguro residencial",
    status: "open" as const,
    createdAt: "12/12/2024",
    assignee: "Anderson Freitas",
  },
  {
    id: "TK005",
    priority: "urgent" as const,
    clientName: "Anderson Silva",
    clientEmail: "spidersilva@email.com",
    subject: "Dúvida sobre cobertura",
    status: "open" as const,
    createdAt: "12/12/2024",
    assignee: "Anderson Freitas",
  },
  {
    id: "TK006",
    priority: "medium" as const,
    clientName: "Familia Total",
    clientEmail: "familiatotal@email.com",
    subject: "Dúvida sobre combo automóvel e residencial",
    status: "open" as const,
    createdAt: "09/12/2024",
    assignee: "Ana Silva",
  },
  {
    id: "TK007",
    priority: "urgent" as const,
    clientName: "Marcos Leite",
    clientEmail: "marcosleite@email.com",
    subject: "Solicitação de alteração",
    status: "open" as const,
    createdAt: "14/12/2024",
    assignee: "Ana Silva",
  },
  {
    id: "TK008",
    priority: "medium" as const,
    clientName: "Pedro Silva",
    clientEmail: "pedrosilva@email.com",
    subject: "Dúvida sobre cobertura",
    status: "open" as const,
    createdAt: "13/12/2024",
    assignee: "João Costa",
  },
  {
    id: "TK009",
    priority: "low" as const,
    clientName: "João Silva",
    clientEmail: "joaosilva@email.com",
    subject: "Sinistro na residência",
    status: "in-progress" as const,
    createdAt: "13/12/2024",
    assignee: "Carlos Lima",
  },
  {
    id: "TK010",
    priority: "urgent" as const,
    clientName: "Edvando Cordeiro",
    clientEmail: "edvandocordeiro@email.com",
    subject: "Solicitação de alteração",
    status: "open" as const,
    createdAt: "14/12/2024",
    assignee: "Ana Silva",
  },
  {
    id: "TK011",
    priority: "urgent" as const,
    clientName: "Leandro Sandro",
    clientEmail: "leandroSandro@email.com",
    subject: "Solicitação de alteração",
    status: "open" as const,
    createdAt: "14/12/2024",
    assignee: "Ana Silva",
  },
  {
    id: "TK012",
    priority: "urgent" as const,
    clientName: "Aníbal Marques",
    clientEmail: "anibalmarques@email.com",
    subject: "Solicitação de alteração",
    status: "open" as const,
    createdAt: "14/12/2024",
    assignee: "Ana Silva",
  },
  {
    id: "TK013",
    priority: "urgent" as const,
    clientName: "Rem[edio da Silva",
    clientEmail: "remedio@email.com",
    subject: "Solicitação de alteração",
    status: "open" as const,
    createdAt: "14/12/2024",
    assignee: "Ana Silva",
  },
  {
    id: "TK014",
    priority: "urgent" as const,
    clientName: "Senhorinha Placida",
    clientEmail: "senhorinhaplacida@email.com",
    subject: "Solicitação de alteração",
    status: "open" as const,
    createdAt: "14/12/2024",
    assignee: "Ana Silva",
  },
  {
    id: "TK015",
    priority: "urgent" as const,
    clientName: "Silvano Vano",
    clientEmail: "silvanovano@email.com",
    subject: "Solicitação de alteração",
    status: "open" as const,
    createdAt: "14/12/2024",
    assignee: "Ana Silva",
  },
  {
    id: "TK016",
    priority: "urgent" as const,
    clientName: "Marcos Leite",
    clientEmail: "marcosleite@email.com",
    subject: "Solicitação de alteração",
    status: "open" as const,
    createdAt: "14/12/2024",
    assignee: "Ana Silva",
  },
  {
    id: "TK017",
    priority: "urgent" as const,
    clientName: "Carlos Careli",
    clientEmail: "carloscareli@email.com",
    subject: "Solicitação de alteração",
    status: "open" as const,
    createdAt: "14/12/2024",
    assignee: "Ana Silva",
  },
  {
    id: "TK018",
    priority: "urgent" as const,
    clientName: "Reinaldo Reis",
    clientEmail: "reinaldoreis@email.com",
    subject: "Solicitação de alteração",
    status: "open" as const,
    createdAt: "14/12/2024",
    assignee: "Ana Silva",
  },
  {
    id: "TK019",
    priority: "urgent" as const,
    clientName: "Simao Simoes",
    clientEmail: "simaosimoes@email.com",
    subject: "Solicitação de alteração",
    status: "open" as const,
    createdAt: "14/12/2024",
    assignee: "Ana Silva",
  },
  {
    id: "TK020",
    priority: "urgent" as const,
    clientName: "Evanildo Leite",
    clientEmail: "evanildoleite@email.com",
    subject: "Solicitação de alteração",
    status: "open" as const,
    createdAt: "14/12/2024",
    assignee: "Ana Silva",
  },
];
